# Generated by Django 2.2.12 on 2020-06-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driver'),
        ('shopping_cart', '0002_order_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='accounts.Driver'),
        ),
    ]
