# Generated by Django 2.2.12 on 2020-06-12 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_driver'),
        ('shopping_cart', '0004_orderitem_is_fulfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping_cart.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='accounts.Vendor'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, default=uuid.uuid1, unique=True)),
                ('customer', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shopping_cart.Basket'),
        ),
    ]
