# Generated by Django 2.2.12 on 2020-06-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200608_1659'),
        ('photos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_aux', models.BooleanField(default=False)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('low_stock', models.BooleanField(default=False)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('mark_as_new', models.BooleanField(default=False)),
                ('new_start', models.DateTimeField(blank=True, null=True)),
                ('new_end', models.DateTimeField(blank=True, null=True)),
                ('not_returnable', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('allow_reviews', models.BooleanField(default=False)),
                ('vendor_comments', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('sales_rate', models.FloatField(blank=True, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('call_for_price', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lenght', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sold', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='users.Acl')),
                ('album', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='photos.Album')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='catalog.Product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.Vendor')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_aux', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, related_name='attributes', to='catalog.Product')),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_aux', models.BooleanField(default=False)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, default=0)),
                ('low_stock', models.BooleanField(default=False)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('mark_as_new', models.BooleanField(default=False)),
                ('new_start', models.DateTimeField(blank=True, null=True)),
                ('new_end', models.DateTimeField(blank=True, null=True)),
                ('not_returnable', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('allow_reviews', models.BooleanField(default=False)),
                ('vendor_comments', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('sales_rate', models.FloatField(blank=True, null=True)),
                ('on_sale', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('call_for_price', models.BooleanField(default=False)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lenght', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sold', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_bundles', to='users.Acl')),
                ('album', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_bundle', to='photos.Album')),
                ('categories', models.ManyToManyField(blank=True, related_name='product_bundles', to='catalog.Category')),
                ('products', models.ManyToManyField(blank=True, related_name='bundels', to='catalog.Product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_bundle', to='accounts.Vendor')),
            ],
            options={
                'verbose_name': 'product bundle',
                'verbose_name_plural': 'product bundles',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.ProductAttribute')),
            ],
            options={
                'verbose_name': 'product attribute value',
                'verbose_name_plural': 'product attribute value',
            },
        ),
    ]
