# Generated by Django 2.2.12 on 2020-06-10 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predefineattributevalue',
            options={'verbose_name': 'predefined attribute value', 'verbose_name_plural': 'predefined attribute values'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'product attribute value', 'verbose_name_plural': 'product attribute values'},
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_values', to='catalog.ProductAttribute'),
        ),
    ]
