# Generated by Django 2.2.12 on 2020-06-09 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lenght',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='products',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='catalog.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='acl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.Acl'),
        ),
    ]
