# Generated by Django 2.2.12 on 2020-06-10 08:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_productattributevalue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid1, unique=True),
        ),
    ]
