# Generated by Django 2.2.12 on 2020-06-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200610_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.PredefineAttributeValue'),
        ),
        migrations.AlterField(
            model_name='predefineattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.ProductAttribute'),
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
