# Generated by Django 2.2.12 on 2020-06-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200608_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Individual-Buyer', 'Individual-Buyer'), ('Wholesale-Buyer', 'Wholesale-Buyer')], max_length=30),
        ),
    ]
